### ISSUE TITLE
P-value result is different from R fisher test

### ISSUE THREAD

**Issue by westhyena** [maclandrol/FisherExact#12]
Hello,
I'm testing this code and comparing with R's fisher test result.
But, the p-value result is different.

Is there a reason or miss implemetation?
or
doesn't matter in fisher test?

I made a simple test code.
```python
import FisherExact
import numpy as np

from rpy2 import robjects
from rpy2.robjects.packages import importr
from rpy2.robjects.numpy2ri import numpy2rpy

ary = np.array([
    [1, 3, 1, 4],
    [3, 5, 1, 3,]
])

stats = importr("stats")
matrix = numpy2rpy(ary)
robjects.r("set.seed(0)")

# R's p-value
p_value1 = stats.fisher_test(matrix)[0][0]

# this repo's p-value
p_value2 = FisherExact.fisher_exact(
    ary,
    alternative="two-sided",
    hybrid=False,
    workspace=200000,
    seed=0
)

"""
p_value1: 0.7932841152655332
p_value2: 0.4857142857142828
"""
```

Thank you.

**Comment by maclandrol** [comment]
Hello @westhyena, this code is not maintained anymore. 

At the time when this package was created, both results were in agreements, although there was a bug in the R version that was corrected much later (here: https://github.com/wch/r-source/commit/636e6822178322c072f40929052767ae91f8fd52#diff-932c33c192b11773a120dfcc542e469f2850179814995437575714e8ae2fa0eaL106). 

That same PR also made a lot of modification to the C code that I haven't looked into.

**Comment by westhyena** [comment]
Thank you for the comment.
