### ISSUE TITLE
Not so much an issue as help for Mac users

### ISSUE THREAD

**Issue by fomightez** [maclandrol/FisherExact#2]
If you try this on a Mac and get an error like so
    `Traceback (most recent call last):`
    `File "Fisher.py", line 3, in <module>`
   `import statlib.fexact as f`

Then you need to recompile by typing `./recompile.sh` in your terminal as [Emmanuel](https://github.com/maclandrol) helped me figure out. But first you'll probably need to install a fortran compiler. You'll know for sure if you run the `./recompile.sh` command in your terminal and get an error abort not finding a compiler such as `pgfortran`.

The easiest place I found to get a fortran compiler was [here](https://gcc.gnu.org/wiki/GFortranBinaries) under `MacOS`.  After downloading the right version for your system, you'll need to unpack it and then click on it to install and lower your security setting on your Mac to allow any software for a few minutes. You can verify it is installed works by typing your terminal 
`gfortran --version`

Now the  the `./recompile.sh` command should run to completion and then `python Fisher.py` should run in your terminal without an error.

**Comment by maclandrol** [comment]
No need to recompile now. The need of fortran compiler mentionned on readme. Thanks
