### ISSUE TITLE
Code fails for python 3.4.3

### ISSUE THREAD

**Issue by nikilwale** [maclandrol/FisherExact#6]
Hi,

I just ran into this error while trying to run the test with Monte Carlo simulation on python 3.4.3 -
  File "/usr/lib64/python3.4/site-packages/FisherExact/Fisher.py", line 130, in fisher_exact
    tmp_res = _fisher_sim(c, replicate, seed, workspace)
  File "/usr/lib64/python3.4/site-packages/FisherExact/Fisher.py", line 243, in _fisher_sim
    for i in xrange(2, n + 1):
NameError: name 'xrange' is not defined

I guess 'xrange' is no longer part of python 3 if I am not mistaken.

Thanks,

**Comment by maclandrol** [comment]
Fixed, in the last commit (84ed6da).

I only tested it on py3.3 and 3.6 though, so I'm keeping the issue open until you confirmed it's working. 

A new version (v1.4.2) was also released on pip (you should purge the previous installation before).

**Comment by nikilwale** [comment]
It works now! Thank you for the quick turn around.
