### ISSUE TITLE
How to cite?

### ISSUE THREAD

**Issue by orena1** [maclandrol/FisherExact#9]
Hi, any idea how to cite your package?

Thanks.

**Comment by maclandrol** [comment]
I have added a zenodo DOI (see readme)

A basic bibtex entry will look like this : 

@article{maclandrol,
title={Fisher's exact test for MxN contingency table}, 
DOI={10.5281/zenodo.2587757},
publisher={Zenodo}, 
author={Emmanuel Noutahi}, 
year={2018}
}
